<div x-data="{ toasts: [], push(toast) { const item = { id: Date.now() + Math.random(), type: toast.type || 'success', message: toast.message }; this.toasts.push(item); window.setTimeout(() => this.dismiss(item.id), 4500); }, dismiss(id) { this.toasts = this.toasts.filter((toast) => toast.id !== id); } }" x-init="<?php if(session('success')): ?> push({ type: 'success', message: <?php echo \Illuminate\Support\Js::from(session('success'))->toHtml() ?> }); <?php endif; ?> <?php if(session('error')): ?> push({ type: 'error', message: <?php echo \Illuminate\Support\Js::from(session('error'))->toHtml() ?> }); <?php endif; ?>" x-on:toast.window="push($event.detail)" class="pointer-events-none fixed inset-x-4 top-4 z-[100] flex max-w-md flex-col gap-3 sm:left-auto sm:right-6 sm:top-6" aria-live="polite" aria-atomic="true">
    <template x-for="toast in toasts" :key="toast.id">
        <div x-show="true" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="translate-y-2 opacity-0 sm:translate-x-4" x-transition:enter-end="translate-y-0 opacity-100 sm:translate-x-0" x-transition:leave="transition ease-in duration-200" x-transition:leave-start="translate-y-0 opacity-100" x-transition:leave-end="translate-y-2 opacity-0 sm:translate-x-4" :class="toast.type === 'error' ? 'border-rose-200 bg-rose-50 text-rose-950' : 'border-emerald-200 bg-white text-slate-900'" class="pointer-events-auto flex items-start gap-3 rounded-2xl border p-4 shadow-[0_18px_45px_-22px_rgba(15,23,42,.45)]" role="status">
            <span :class="toast.type === 'error' ? 'bg-rose-600' : 'bg-emerald-700'" class="grid h-7 w-7 shrink-0 place-items-center rounded-full text-sm font-bold text-white" x-text="toast.type === 'error' ? '!' : '✓'"></span>
            <div class="min-w-0 flex-1"><p class="text-sm font-bold" x-text="toast.type === 'error' ? 'Tindakan belum berhasil' : 'Berhasil'"></p><p class="mt-0.5 text-sm leading-5 text-slate-600" x-text="toast.message"></p></div>
            <button type="button" x-on:click="dismiss(toast.id)" class="-mr-1 -mt-1 grid h-7 w-7 place-items-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-700" aria-label="Tutup notifikasi">×</button>
        </div>
    </template>
</div>
<?php /**PATH C:\laragon\www\sideswita 2\resources\views/components/toast-notifications.blade.php ENDPATH**/ ?>